export const FIND_CITY_BY_NAME_REQUEST = 'FIND_CITY_BY_NAME_REQUEST';
export const FIND_CITY_BY_NAME_SUCCESS = 'FIND_CITY_BY_NAME_SUCCESS';
export const FIND_CITY_BY_NAME_ERROR = 'FIND_CITY_BY_NAME_ERROR';

export const ADD_CITY_TO_FAVORITE = 'ADD_CITY_TO_FAVORITE';

export const SEARCH_VALUE_CHANGE = 'SEARCH_VALUE_CHANGE';
